import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../store/store";

// TODO: fix ts errors in formdata on responess

export interface Web3State {
  walletKey: string;
}

const initialState: Web3State = {
  walletKey: "",
};

export const web3Slice = createSlice({
  name: "web3",
  initialState,
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {} = web3Slice.actions;

export default web3Slice.reducer;
